development:
  adapter: postgresql
  encoding: unicode
  database: rails-wercker-heroku_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: rails-wercker-heroku_test
  pool: 5
  host: localhost
